---
- hosts: test00
  collections:
    - fortinet.fortios

  network_os: fortinet.fortios.fortios
  connection: httpapi

  tasks:
    - name: GET FACTS
      fortios_facts:
        vdom: root
        gather_subset:
          - fact: 'system_status_select'
