---
- hosts: test00
  collections:
    - fortinet.fortios
  connection: httpapi

  vars:
    ansible_network_os: fortinet.fortios.fortios


  tasks:
    - name: GET FACTS
      fortios_facts:
        vdom: root
        gather_subset:
          - fact: 'system_status_select'
